name: eval_blurball
device: cuda  # CPU is not supported by the detector
gpus: [0]
vis_result: True  # Enable visualization of results
vis_hm: True  # Enable heatmap visualization
vis_traj: True  # Enable trajectory visualization
best_model_name: best_model.pth.tar
# model_dir will be taken from the main config
model_path: 
split: test
fp1_filename: # dummy
eval:
  score_threshold: 0.5
  dist_threshold: 4

